import { PodcastEpisode, BlogPost } from "@/types";

export const podcastEpisodes: PodcastEpisode[] = [
  {
    slug: "bitcoin-halving-2024-what-to-expect",
    title: "Bitcoin Halving 2024 — What to Expect",
    description: "Brian and Ross dive deep into the upcoming Bitcoin halving event, historical patterns, and what it could mean for the crypto market going forward.",
    date: "2024-03-15",
    duration: "45 min",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    youtubeUrl: "https://youtube.com",
    podbeanUrl: "https://podbean.com",
  },
  {
    slug: "altcoin-season-is-it-here",
    title: "Altcoin Season — Is It Here?",
    description: "We break down the signs of an altcoin season, which projects are leading the charge, and how to position your portfolio for maximum upside.",
    date: "2024-03-01",
    duration: "38 min",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    youtubeUrl: "https://youtube.com",
    podbeanUrl: "https://podbean.com",
  },
  {
    slug: "defi-explained-for-beginners",
    title: "DeFi Explained for Beginners",
    description: "A beginner-friendly walkthrough of decentralized finance — what it is, how it works, and why it matters for the future of money.",
    date: "2024-02-15",
    duration: "52 min",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    youtubeUrl: "https://youtube.com",
    podbeanUrl: "https://podbean.com",
  },
  {
    slug: "crypto-regulations-2024-update",
    title: "Crypto Regulations — 2024 Update",
    description: "Brian uses his legal background to break down the latest regulatory developments in crypto, what they mean for investors, and where the industry is headed.",
    date: "2024-02-01",
    duration: "41 min",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    youtubeUrl: "https://youtube.com",
    podbeanUrl: "https://podbean.com",
  },
  {
    slug: "ethereum-layer-2-deep-dive",
    title: "Ethereum Layer 2 Deep Dive",
    description: "We explore the Layer 2 ecosystem on Ethereum — Arbitrum, Optimism, Base, and more. Which ones are winning and why?",
    date: "2024-01-15",
    duration: "49 min",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    youtubeUrl: "https://youtube.com",
    podbeanUrl: "https://podbean.com",
  },
  {
    slug: "top-crypto-picks-for-2024",
    title: "Our Top Crypto Picks for 2024",
    description: "Brian and Ross share their top cryptocurrency picks for the year ahead, with analysis on fundamentals, technology, and market positioning.",
    date: "2024-01-01",
    duration: "55 min",
    spotifyUrl: "https://open.spotify.com",
    appleUrl: "https://podcasts.apple.com",
    youtubeUrl: "https://youtube.com",
    podbeanUrl: "https://podbean.com",
  },
];

export const blogPosts: BlogPost[] = [
  {
    slug: "understanding-bitcoin-halving",
    title: "Understanding Bitcoin Halving and Its Impact on Price",
    excerpt: "Every four years, Bitcoin undergoes a halving event that cuts the mining reward in half. Here's what that means for investors.",
    content: "Bitcoin halving is one of the most anticipated events in the cryptocurrency world. Every 210,000 blocks (approximately every four years), the reward for mining new blocks is halved, reducing the rate at which new bitcoins are created.\n\nThis mechanism is built into Bitcoin's protocol and serves as a deflationary measure, ensuring that Bitcoin's total supply will never exceed 21 million coins.\n\nHistorically, each halving has preceded significant bull runs in Bitcoin's price, though past performance doesn't guarantee future results.",
    date: "2024-03-10",
    author: "Brian McCoy",
    tags: ["Bitcoin", "Halving", "Investment"],
  },
  {
    slug: "beginners-guide-to-defi",
    title: "A Beginner's Guide to DeFi",
    excerpt: "Decentralized Finance is reshaping how we think about money. Learn the basics of DeFi and how to get started.",
    content: "Decentralized Finance, commonly known as DeFi, represents a shift from traditional centralized financial systems to peer-to-peer finance enabled by decentralized technologies built on blockchain networks.\n\nDeFi platforms allow people to lend or borrow funds, trade cryptocurrencies, earn interest, and more — all without the need for traditional intermediaries like banks.\n\nKey DeFi concepts include liquidity pools, yield farming, decentralized exchanges (DEXs), and smart contracts.",
    date: "2024-02-20",
    author: "Ross Eaton",
    tags: ["DeFi", "Beginners", "Education"],
  },
  {
    slug: "crypto-tax-guide-2024",
    title: "Crypto Tax Guide for 2024",
    excerpt: "Navigating crypto taxes can be complex. Here's what you need to know for the 2024 tax season.",
    content: "As cryptocurrency becomes more mainstream, tax authorities worldwide are paying closer attention to crypto transactions. In the United States, the IRS treats cryptocurrency as property, meaning every transaction could potentially trigger a taxable event.\n\nWhether you're trading, mining, staking, or earning crypto, it's important to understand your tax obligations. Key events include selling crypto for fiat, trading one crypto for another, and receiving crypto as payment.",
    date: "2024-02-05",
    author: "Brian McCoy",
    tags: ["Taxes", "Legal", "Guide"],
  },
  {
    slug: "solana-vs-ethereum-2024",
    title: "Solana vs Ethereum: The 2024 Comparison",
    excerpt: "Two of the biggest smart contract platforms go head to head. We compare speed, fees, ecosystem, and future outlook.",
    content: "The competition between Solana and Ethereum continues to be one of the most interesting narratives in crypto. While Ethereum remains the dominant smart contract platform with the largest ecosystem, Solana has made significant strides in speed and user experience.\n\nEthereum's Layer 2 solutions are helping address scalability concerns, while Solana offers high throughput natively. Both ecosystems have their strengths and trade-offs.",
    date: "2024-01-20",
    author: "Ross Eaton",
    tags: ["Solana", "Ethereum", "Comparison"],
  },
];
